name: Monitors

on:
  push:
  workflow_dispatch:

jobs:
  locate:
    runs-on: ubuntu-latest

    outputs:
      disabled: ${{ steps.set-disabled.outputs.disabled }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install NPM dependencies
        run: npm ci

      - name: Set disabled monitors list
        id: set-disabled
        run: |
          DISABLED=$(npm run disabled)
          echo $DISABLED
          echo "disabled=$DISABLED" >> $GITHUB_OUTPUT

      - name: Set job matrix from located monitors
        id: set-matrix
        run: |
          MONITORS=$(npm run locate)
          echo $MONITORS
          echo "matrix={\"monitor\":$MONITORS}" >> $GITHUB_OUTPUT

      - name: Display outputs
        run: |
          echo ${{ steps.set-disabled.outputs.disabled }}
          echo ${{ steps.set-matrix.outputs.matrix }}

  monitor:
    needs: locate

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.locate.outputs.matrix) }}
      max-parallel: 20

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Disable checksum offload
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        # https://github.com/actions/runner-images/issues/1187#issuecomment-686735760
        # Fixes networking fetch instability
        run: sudo ethtool -K eth0 tx off rx off

      - name: Disable AppArmor
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        # https://github.com/puppeteer/puppeteer/pull/13196
        # Fixes Puppeteer sandboxing being blocked
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Checkout repository
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        uses: actions/checkout@v4

      - name: Use Node.js
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        run: npm ci

      - name: Run monitor
        if: ${{ !contains(fromJson(needs.locate.outputs.disabled), matrix.monitor) }}
        run: npm run monitor -- ${{ matrix.monitor }}
